name: EasyCommandAutofill
main: jasonwynn10\EasyCommandAutofill\Main
src-namespace-prefix: jasonwynn10\EasyCommandAutofill
version: 3.0.2
api: [4.0.0, 5.0.0]
description: "A plugin which adds commands to the client's autofill by parsing usage messages"
author: "jasonwynn10"